In [1]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}

In [2]:
# get the keys of the documents and store it in the list
key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [3]:
# Extract the category of the key documents and store it 
categories = []
for document in documents:
    category = document.split(': ')[1]
    categories.append(category)

categories

['Pandas Basics', 'Data Visualization', 'Sales Analysis']

In [4]:
# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [5]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = { term for document in documents for term in document.split() }
print(unique_terms)

{'Visualization', 'Sales', 'Tutorial:', 'Analysis', 'Article:', 'Pandas', 'Study:', 'Data', 'Basics', 'Case'}


In [6]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []
    for document in documents:
        if term in document:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)
        
# display the result of the matrix
doc_term_matrix

{'Visualization': [0, 1, 0],
 'Sales': [0, 0, 1],
 'Tutorial:': [0, 1, 0],
 'Analysis': [0, 0, 1],
 'Article:': [1, 0, 0],
 'Pandas': [1, 0, 0],
 'Study:': [0, 0, 1],
 'Data': [0, 1, 0],
 'Basics': [1, 0, 0],
 'Case': [0, 0, 1]}

In [7]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['Basics'])    
v2 = np.array(doc_term_matrix['Pandas'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
[document for document in v3 * docs_array if document]

[1 0 0]
[1 0 0]
-------
[1 0 0]


['This article covers the basics of using Pandas in Python.']

In [8]:
# find the document for those have at least one word
v3 = v1 | v2
print(v3)
[document for document in v3 * docs_array if document]

[1 0 0]


['This article covers the basics of using Pandas in Python.']